-- AlterEnum
ALTER TYPE "Market" ADD VALUE 'CLEAN_SHEET_HOME';
ALTER TYPE "Market" ADD VALUE 'CLEAN_SHEET_AWAY';
ALTER TYPE "Market" ADD VALUE 'WIN_TO_NIL_HOME';
ALTER TYPE "Market" ADD VALUE 'WIN_TO_NIL_AWAY';
ALTER TYPE "Market" ADD VALUE 'TO_WIN_EITHER_HALF';
