// Type bridge for the calibration Postgres schema.
// These models exist in schema.prisma and WILL be generated by Prisma once the
// user runs: prisma migrate dev --name add-calibration-schema
//
// Until then, this file provides structural typings so the CalibrationRepository
// compiles against the expected Prisma shape without relying on generated code
// that does not exist yet.
import type { StrategyChannel, Prisma } from '@evcore/db';

export type CalibrationReportCreateInput = {
  channel: StrategyChannel;
  competitionCode?: string | null;
  startDate: Date;
  endDate: Date;
  betCount: number;
  brierScore: Prisma.Decimal | number | string;
  calibrationError: Prisma.Decimal | number | string;
  roi: Prisma.Decimal | number | string;
  evBins?: Prisma.JsonValue;
  triggeredBy?: string;
};

export type CalibrationReportRecord = {
  id: string;
  channel: StrategyChannel;
  competitionCode: string | null;
  startDate: Date;
  endDate: Date;
  betCount: number;
  brierScore: Prisma.Decimal;
  calibrationError: Prisma.Decimal;
  roi: Prisma.Decimal;
  createdAt: Date;
};

export type ChannelTuningResultCreateInput = {
  channel: StrategyChannel;
  competitionCode?: string | null;
  configSnapshot: Prisma.JsonValue;
  betCount: number;
  roi: Prisma.Decimal | number | string;
  hitRate: Prisma.Decimal | number | string;
  maxDrawdown: Prisma.Decimal | number | string;
  improved: boolean;
};

export type ChannelTuningResultRecord = {
  id: string;
  channel: StrategyChannel;
  roi: Prisma.Decimal;
  hitRate: Prisma.Decimal;
  maxDrawdown: Prisma.Decimal;
  improved: boolean;
  appliedAt: Date | null;
  createdAt: Date;
};

// Extends PrismaClient with the calibration-schema tables.
// Replace with the generated import after running: prisma migrate dev + prisma generate
export type PrismaClientWithCalibration = {
  calibrationReport: {
    create(args: {
      data: CalibrationReportCreateInput;
      select: { id: true };
    }): Promise<{ id: string }>;
    findMany(args: {
      where?: { channel?: StrategyChannel };
      orderBy?: { createdAt: 'asc' | 'desc' };
      take?: number;
      select: {
        id: true;
        channel: true;
        competitionCode: true;
        startDate: true;
        endDate: true;
        betCount: true;
        brierScore: true;
        calibrationError: true;
        roi: true;
        createdAt: true;
      };
    }): Promise<CalibrationReportRecord[]>;
  };
  channelTuningResult: {
    create(args: {
      data: ChannelTuningResultCreateInput;
      select: { id: true };
    }): Promise<{ id: string }>;
    findMany(args: {
      where?: { channel?: StrategyChannel };
      orderBy?: { createdAt: 'asc' | 'desc' };
      take?: number;
      select: {
        id: true;
        channel: true;
        roi: true;
        hitRate: true;
        maxDrawdown: true;
        improved: true;
        appliedAt: true;
        createdAt: true;
      };
    }): Promise<ChannelTuningResultRecord[]>;
  };
};
