export type SupportConversationStatus = "OPEN" | "CLOSED";

export type SupportAttachmentKind = "IMAGE" | "AUDIO" | "FILE";

export type SupportAttachment = {
  kind: SupportAttachmentKind;
  // Presigned, short-lived (~15min) — regenerated by the backend on every
  // read/broadcast, never a permanent link. Re-fetch the conversation if a
  // preview 403s after sitting open a long time.
  url: string;
  mimeType: string;
  sizeBytes: number;
  fileName: string | null;
  durationMs: number | null;
  width: number | null;
  height: number | null;
};

export type SupportMessage = {
  id: string;
  conversationId: string;
  senderId: string;
  senderRole: "ADMIN" | "OPERATOR";
  senderUsername: string;
  content: string | null;
  attachment?: SupportAttachment | null;
  createdAt: string;
  // Set by the backend once automated messages ship (welcome, reminders…) —
  // absent today, so every check below treats undefined as "STANDARD".
  kind?: "STANDARD" | "AUTOMATED";
  // Frontend-only: optimistic messages carry this while in flight, dropped
  // once the server confirms them. Never present on a message read from the
  // API.
  status?: "sending" | "failed";
  // Frontend-only, "sending" only: 0-100 upload progress for an attachment
  // still being PUT to storage (text-only or already-confirmed messages
  // don't carry this).
  uploadProgress?: number;
};

export type TypingEvent = {
  conversationId: string;
  userId: string;
  username: string;
  role: "ADMIN" | "OPERATOR";
  isTyping: boolean;
};

export type SupportConversation = {
  id: string;
  userId: string;
  status: SupportConversationStatus;
  userReadAt: string | null;
  adminReadAt: string | null;
  lastMessageAt: string;
  createdAt: string;
};

export type SupportConversationSummary = SupportConversation & {
  username: string;
  fullName: string;
  avatarUrl: string | null;
  lastMessage: SupportMessage | null;
  unreadCount: number;
};

export type OwnConversationResponse = {
  conversation: SupportConversation;
  messages: SupportMessage[];
  hasMore: boolean;
};

export type SupportMessagePage = {
  messages: SupportMessage[];
  hasMore: boolean;
};

export type AttachmentUploadUrlResponse = {
  objectKey: string;
  uploadUrl: string;
  expiresInSeconds: number;
};
