// Channel strategy config now lives in the pure core
// (@evcore/analysis-core/strategies). Re-exported here so existing imports
// keep resolving unchanged.
export {
  DOMINANT_MIN_MARGIN,
  FIRST_HALF_WINNER_MIN_MARGIN,
  BTTS_NO_CONFIG,
  getBttsNoConfig,
  CHANNEL_STRATEGY_CONFIG_CHANNELS,
  CHANNEL_STRATEGY_CONFIG,
  CLEAN_SHEET_CONFIG,
  WIN_EITHER_HALF_CONFIG,
  WIN_TO_NIL_CONFIG,
  FIRST_HALF_CONFIG,
  DOUBLE_CHANCE_CONFIG,
  HALF_TIME_FULL_TIME_CONFIG,
  GOALS_CONFIG,
  getGoalsLineConfigs,
  TEAM_TOTAL_CONFIG,
  getTeamTotalLineConfigs,
  CONSENSUS_CONFIG,
  AVOID_CONFIG,
  getChannelStrategyConfig,
  type BttsNoLeagueConfig,
  type ChannelStrategyLeagueConfig,
  type ChannelStrategyConfigChannel,
  type GoalsLine,
  type GoalsSide,
  type GoalsLineConfig,
  type GoalsLeagueConfig,
  type TeamTotalTeam,
  type TeamTotalLine,
  type TeamTotalSide,
  type TeamTotalLineConfig,
  type TeamTotalLeagueConfig,
  getResultTotalGoalsLineConfigs,
  type ResultTotalGoalsSide,
  type ResultTotalGoalsLine,
  type ResultTotalGoalsLineConfig,
  getOverUnderHtLineConfigs,
  type OverUnderHtLine,
  type OverUnderHtSide,
  type OverUnderHtLineConfig,
  getResultBttsPickConfigs,
  type ResultBttsSide,
  type ResultBttsOutcome,
  type ResultBttsPickConfig,
  type ResultBttsLeagueConfig,
  getDrawNoBetConfig,
  DRAW_NO_BET_CONFIG,
  DRAW_NO_BET_DEFAULT,
} from '@evcore/analysis-core';
